### ISSUE TITLE
Super awesome!! What about monorepo with 2 nextjs apps deploying with serverless-next

### ISSUE THREAD

**Issue by SavageWilliam** [fillipvt/portfolio#2]
I haven't yet had experience with deployment using now. From your `Now.json` it looks pretty slick! We're using [serverless-next](https://serverless.com/blog/serverless-nextjs/), its super neat! 

However I can see a lot of the heavy lifting is done by your now.json, and I'm struggling to work out how to achieve the same routing without now & with our serverless-next infra.

I don't suppose you've worked with this technology / have ideas around achieving a monorepo with 2 nextjs apps deployed to same domain without now?

**Comment by fev4** [comment]
Hey!

Sadly I don't have any experience with serverless-next.

I've moved away from the monorepo structure and I'm now using a single next.js app for my current needs. This makes configuration way easier and the now.json in some cases is uneeded.

The not-so-recently implemented [api routes](https://nextjs.org/docs/api-routes/introduction) plus [dynamic routing](https://nextjs.org/docs/api-routes/dynamic-api-routes), and the new [data fetching](https://nextjs.org/docs/basic-features/data-fetching) techniques make the monorepo structure less and less desireable for me.

In that sense I'll be updating this repo to reflect that once I'm done with one of my personal projects.

Hope this is a bit useful!
